// Code generated by INKWASM BUILD; DO NOT EDIT
(() => {

})();
// Code generated by INKWASM BUILD; DO NOT EDIT
(() => {
	Object.assign(go.importObject.go, {

		"github.com/inkeliz/giowebview/webview.__log": (sp) => {
			console.log(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8))

		},

		"github.com/inkeliz/giowebview/webview.__querySelector": (sp) => {
			let r = globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).querySelector(globalThis.inkwasm.Load.String(go, sp, 24))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 40, r)
		},

		"github.com/inkeliz/giowebview/webview.__createElement": (sp) => {
			let r = document.createElement(globalThis.inkwasm.Load.String(go, sp, 8))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 24, r)
		},

		"github.com/inkeliz/giowebview/webview.__setAttribute": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).setAttribute(globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.String(go, sp, 40))

		},

		"github.com/inkeliz/giowebview/webview.__setInnerText": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).innerText = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__prepend": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).prepend(globalThis.inkwasm.Load.InkwasmObject(go, sp, 24))

		},

		"github.com/inkeliz/giowebview/webview.__removeChild": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).removeChild(globalThis.inkwasm.Load.InkwasmObject(go, sp, 24))

		},

		"github.com/inkeliz/giowebview/webview.__setStyleWidth": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.width = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStyleHeight": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.height = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStylePosition": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.position = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStyleZIndex": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.zIndex = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStyleBorder": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.border = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStyleDisplay": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.display = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStyleTop": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.top = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setStyleLeft": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).style.left = globalThis.inkwasm.Load.String(go, sp, 24)

		},

		"github.com/inkeliz/giowebview/webview.__setSrc": (sp) => {
			globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).src = globalThis.inkwasm.Load.String(go, sp, 24)

		},

	})
})();
