// Code generated by INKWASM BUILD; DO NOT EDIT
#include "textflag.h"

TEXT ·log(SB), NOSPLIT, $0
	JMP ·_log(SB)
	RET

TEXT ·querySelector(SB), NOSPLIT, $0
	JMP ·_querySelector(SB)
	RET

TEXT ·createElement(SB), NOSPLIT, $0
	JMP ·_createElement(SB)
	RET

TEXT ·setAttribute(SB), NOSPLIT, $0
	JMP ·_setAttribute(SB)
	RET

TEXT ·setInnerText(SB), NOSPLIT, $0
	JMP ·_setInnerText(SB)
	RET

TEXT ·prepend(SB), NOSPLIT, $0
	JMP ·_prepend(SB)
	RET

TEXT ·removeChild(SB), NOSPLIT, $0
	JMP ·_removeChild(SB)
	RET

TEXT ·setStyleWidth(SB), NOSPLIT, $0
	JMP ·_setStyleWidth(SB)
	RET

TEXT ·setStyleHeight(SB), NOSPLIT, $0
	JMP ·_setStyleHeight(SB)
	RET

TEXT ·setStylePosition(SB), NOSPLIT, $0
	JMP ·_setStylePosition(SB)
	RET

TEXT ·setStyleZIndex(SB), NOSPLIT, $0
	JMP ·_setStyleZIndex(SB)
	RET

TEXT ·setStyleBorder(SB), NOSPLIT, $0
	JMP ·_setStyleBorder(SB)
	RET

TEXT ·setStyleDisplay(SB), NOSPLIT, $0
	JMP ·_setStyleDisplay(SB)
	RET

TEXT ·setStyleTop(SB), NOSPLIT, $0
	JMP ·_setStyleTop(SB)
	RET

TEXT ·setStyleLeft(SB), NOSPLIT, $0
	JMP ·_setStyleLeft(SB)
	RET

TEXT ·setSrc(SB), NOSPLIT, $0
	JMP ·_setSrc(SB)
	RET
