// Code generated by INKWASM BUILD; DO NOT EDIT
#include "textflag.h"

TEXT ·__log(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·log(SB), NOSPLIT, $0
	JMP ·_log(SB)
	RET

TEXT ·__querySelector(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·querySelector(SB), NOSPLIT, $0
	JMP ·_querySelector(SB)
	RET

TEXT ·__createElement(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·createElement(SB), NOSPLIT, $0
	JMP ·_createElement(SB)
	RET

TEXT ·__setAttribute(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setAttribute(SB), NOSPLIT, $0
	JMP ·_setAttribute(SB)
	RET

TEXT ·__setInnerText(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setInnerText(SB), NOSPLIT, $0
	JMP ·_setInnerText(SB)
	RET

TEXT ·__prepend(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·prepend(SB), NOSPLIT, $0
	JMP ·_prepend(SB)
	RET

TEXT ·__removeChild(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·removeChild(SB), NOSPLIT, $0
	JMP ·_removeChild(SB)
	RET

TEXT ·__setStyleWidth(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleWidth(SB), NOSPLIT, $0
	JMP ·_setStyleWidth(SB)
	RET

TEXT ·__setStyleHeight(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleHeight(SB), NOSPLIT, $0
	JMP ·_setStyleHeight(SB)
	RET

TEXT ·__setStylePosition(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStylePosition(SB), NOSPLIT, $0
	JMP ·_setStylePosition(SB)
	RET

TEXT ·__setStyleZIndex(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleZIndex(SB), NOSPLIT, $0
	JMP ·_setStyleZIndex(SB)
	RET

TEXT ·__setStyleBorder(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleBorder(SB), NOSPLIT, $0
	JMP ·_setStyleBorder(SB)
	RET

TEXT ·__setStyleDisplay(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleDisplay(SB), NOSPLIT, $0
	JMP ·_setStyleDisplay(SB)
	RET

TEXT ·__setStyleTop(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleTop(SB), NOSPLIT, $0
	JMP ·_setStyleTop(SB)
	RET

TEXT ·__setStyleLeft(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setStyleLeft(SB), NOSPLIT, $0
	JMP ·_setStyleLeft(SB)
	RET

TEXT ·__setSrc(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setSrc(SB), NOSPLIT, $0
	JMP ·_setSrc(SB)
	RET
